myproject/models.py
###############################
####### DATABASE MODELS #######
###############################

# Set up db inside the __init__.py in myproject folder
from myproject import db

class Puppy(db.Model):

    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)

    # One to One: Puppy can have only one Owner
    owner = db.relationship('Owner',backref='puppy',uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return "Puppy name is "+self.name+" and owner is "+self.owner.name
        else:
            return "Puppy name is "+self.name +" and has no owner assigned yet"


class Owner(db.Model):

    __tablename__ ="owners"
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return "Owner name:" + self.name

myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Name of the Owner: ')
    pup_id = IntegerField("Id of Puppy: ")
    submit = SubmitField('Add Owner')

myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Name of the Puppy:')
    submit = SubmitField('Add puppy')

class DelForm(FlaskForm):

    id = IntegerField("Id number of Puppy to remove: ")
    submit = SubmitField("Remove Puppy")

myproject/__init__.py
import os
from flask import Flask, Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

# Register the blueprints
# Defined after we have defined DB
from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint


app.register_blueprint(owners_blueprint,url_prefix='/owners')
app.register_blueprint(puppies_blueprint,url_prefix='/puppies')

myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprint = Blueprint('owners',__name__, template_folder='templates/owners')

@owners_blueprint.route('/add', methods=['GET', 'POST'])
def add():

    form = AddForm()
    if form.validate_on_submit():

        name = form.name.data
        pup_id = form.pup_id.data

        new_owner = Owner(name,pup_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add_owner.html',form=form)

myproject/puppies/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm

puppies_blueprint = Blueprint('puppies',__name__, template_folder='templates/puppies')

@puppies_blueprint.route('/add', methods=['GET','POST'])
def add():

    form = AddForm()
    if form.validate_on_submit():

        name = form.name.data

        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('add.html',form=form)


@puppies_blueprint.route('/list')
def list():

    puppies = Puppy.query.all() # return type is a list
    return render_template('list.html',puppies=puppies)


@puppies_blueprint.route('/delete', methods=["GET","POST"])
def delete():

    form = DelForm()

    if form.validate_on_submit():

        id = form.id.data
        pup = Puppy.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))

    return render_template('delete.html',form=form)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <title></title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>

<body>
  <nav class='navbar navbar-expand-lg navbar-light bg-light'>
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.add') }}">Add Pup</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.list') }}">List of Pups</a>
      <a class="nav-item nav-link" href="{{ url_for('puppies.delete') }}">Delete Pup</a>
      <a class="nav-item nav-link" href="{{ url_for('owners.add') }}">Add Owner</a>
    </div>
  </nav>

  {% block content  %}

  {% endblock  %}

</body>

</html>

myproject/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1>Welcome to our adoption page</h1>
  <p>Please select one of the links from the nav bar</p>
</div>

{% endblock %}